### ISSUE TITLE
Estrutura de Mensagens

### ISSUE THREAD

**Issue by FelipeRos19** [RabbitHoleRP/Common#5]
Alterar na estrutura de mensagens de Player para CommandSender, assim permitindo 1 único método enviar mensagem para console e para jogadores, ou adicionar um método para envio de mensagens especificamente para instância Console.

**Comment by gabrizete** [comment]
Acho interessante alterar os argumentos `Player` dos métodos de `Messages.java`  para `CommandSender`, deixa eles mais flexíveis.
